In [1]:
import numpy as np
import pandas as pd

In [2]:
a = [1,2,3,43]

type(a)

list

In [3]:
num = np.array([10,20,30,40])
num

array([10, 20, 30, 40])

In [4]:
name = np.array(["ali", "waseem", "ramzan"])

display(name)

array(['ali', 'waseem', 'ramzan'], dtype='<U6')

In [5]:
arr =  np.array([1,2,3,4,5])    # this is a array

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)   #  we can check type of array

numpy.ndarray

In [8]:
arr1 = np.array((1,2,3,4,5))   #  This is a Tuple

In [9]:
print(arr1)

[1 2 3 4 5]


In [10]:
type(arr1)

numpy.ndarray

In [11]:
arr2 = [ 1,2,3,4,5]   #  this is a list

In [12]:
type(arr2)

list

In [13]:
arr = np.array(arr2)   #  in numpy array we can pass dictionary,list,tuple and convert into array.

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr

array([1, 2, 3, 4, 5])

# 0-D Arrays


In [16]:
#  0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [17]:
import numpy as np
ar = np.array(10)
ar

array(10)

In [18]:
type(ar)

numpy.ndarray

In [19]:
ar.ndim

0

In [20]:
import numpy as icode

arr = icode.array(100)

In [21]:
print(arr)

100


In [22]:
type(arr)

numpy.ndarray

In [23]:
arr.ndim

0

# 1-D Arrays


In [24]:
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.



In [25]:
arr = np.array([1, 2, 3, 4, 5])


In [26]:
arr

array([1, 2, 3, 4, 5])

In [27]:
arr.ndim

1

# 2-D Arrays


In [28]:
# An array that has 1-D arrays as its elements is called a 2-D array.

# These are often used to represent matrix or 2nd order tensors.

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [30]:
arr.ndim

2

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

# 3-D arrays


In [32]:
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.

#These are often used to represent a 3rd order tensor.

In [33]:
#height, width, depth

In [34]:
#frame, height, width, depth

In [35]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[1, 2, 3], [4, 5, 6]]])


In [36]:
arr.ndim

3

In [37]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

# Higher Dimensional Arrays


In [38]:
# An array can have any number of dimensions.

# When the array is created, you can define the number of dimensions by using the ndmin argument.

In [39]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1, 2, 3, 4], ndmin=4)
arr

array([[[[1, 2, 3, 4]]]])

In [40]:
arr.ndim

4

In [41]:
print('number of dimensions :', arr.ndim)


number of dimensions : 4


#  NumPy Array Indexing


In [42]:
# Array indexing is the same as accessing an array element.

# You can access an array element by referring to its index number.

# The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [43]:
import numpy as np


In [44]:
arr = np.array([1, 2, 3, 4])

arr[-2]    # we give index and get the number/value

3

In [45]:
arr[3]

4

In [46]:
arr

array([1, 2, 3, 4])

In [47]:
# Get third and fourth elements from the following array .

print(arr[0], arr[0])

1 1


In [48]:
# Get third and fourth elements from the following array and add them.

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])     #  3+4

print(arr > 2)

7
[False False  True  True]


# Access 2-D Arrays


In [49]:
# To access elements from 2-D arrays we can use comma separated integers representing the dimension 
# and the index of the element.




In [50]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
# We got 3 in 1st dim

arr[0,3]

4

In [52]:
arr[1,1]

7

In [53]:
# we got 9 in dim 2nd

In [54]:
arr[1,3]

9

# Access 3-D Arrays


In [55]:
# To access elements from 3-D arrays we can use comma separated 
# integers representing the dimensions and the index of the element.



In [56]:
# Access the third element of the second array of the first array:

import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
arr[0,1,2]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


6

In [57]:
arr[1,1,1]

11

In [58]:
arr[1,0,0]

7

# Negative Indexing


In [59]:
# Use negative indexing to access an array from the end.



In [60]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])


In [61]:
arr[-2, -5]

1

In [62]:
print('Last element from 2nd dim: ', arr[-1, -5])


Last element from 2nd dim:  6


In [63]:
arr[1,4]

10

# NumPy Array Slicing


In [64]:
import numpy as np

# Slicing arrays

In [65]:
# We pass slice instead of index like this: [start:end].

# We can also define the step, like this: [start:end:step].

# If we don't pass start its considered 0

# If we don't pass end its considered length of array in that dimension

# If we don't pass step its considered 1

In [ ]:
array_name[starting : ending : step] # 100, 20 to 60

In [ ]:
array[ : :1] # 1,2,3,4,5

In [79]:
# Slice elements from index 1 to index 5 from the following array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[1:4]

array([2, 3, 4])

In [86]:
arr[ : : 4]

array([1, 5])

In [87]:
arr[ : 4]

array([1, 2, 3, 4])

In [88]:
arr[0:4]  # 0, n-1

array([1, 2, 3, 4])

In [67]:
# Slice elements from index 4 to the end of the array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[4:]

array([5, 6, 7])

In [89]:
# Slice elements from the beginning to index 4 (not included):

arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[ : 4]

array([1, 2, 3, 4])

In [92]:
# Slice from the index 3 from the end to index 1 from the end:

arr = np.array([1, 2, 3, 4, 5, 6, 7]) # not n-1 indexing

#arr[-3:-1]

arr[-5 : -2]

array([3, 4, 5])

# STEP


In [70]:
# Use the step value to determine the step of the slicing:



In [94]:
# Return every other element from index 1 to index 5:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[1:5:2]

array([2, 4])

In [95]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])


[1 3 5 7]


# Slicing 2-D Arrays


In [73]:
# From the second element, slice elements from index 1 to index 4 (not included):



In [102]:
arr = np.array([[1, 2, 3, 4, 5], # 0 index
                [6, 7, 8, 9, 10]])# 1 index 

#print(arr[0, 1:3]) #positive indexing n-1

print(arr[1 , : -1])
print()
print(arr[1,-1 ])
print()
print(arr[1, 4 ])
print()
print(arr[1, 4: ])

[6 7 8 9]

10

10

[10]


In [103]:
arr[0,1:3]

array([2, 3])

In [104]:
print(arr[0:2, 2])  


[3 8]


In [111]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

a1 = (arr[1:2, 1:4])

print(type(a1))
print(a1)
a1.ndim

<class 'numpy.ndarray'>
[[7 8 9]]


2

In [112]:
arr[0:2,1:4]   # 1st element indicate of index and , 2nd is doing slicing

array([[2, 3, 4],
       [7, 8, 9]])